[project]
name = "aimer"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django[argon2]==6.0.2",
    "django-rich==2.2.0",
    "python-dotenv==1.2.1",
    "argon2-cffi==25.1.0",
    "uvicorn==0.40.0",
    "docling[vlm]==2.72.0",
    "fastembed==0.7.4",
    "transformers==4.57.6",
    "huggingface-hub",
    "hf-xet",
    "langchain-core==1.2.8",
    "langchain-community==0.4.1",
    "langchain-qdrant==1.1.0",
    "langchain-docling==2.0.0",
    "langchain-ollama==1.0.1",
    "langgraph==1.0.7",
    "langgraph-checkpoint-sqlite==3.0.3",
    "numpy",
    "pydantic==2.12.5",
    "pypdf==6.6.2",
    "qdrant-client==1.16.2",
    "tqdm==4.67.2",
    "pytest==9.0.2",
    "coverage==7.13.3",
]
